# Generated by Django 5.2.1 on 2025-09-09 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0005_emailtracking'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscribers',
            new_name='Subscriber',
        ),
    ]
