# Generated by Django 5.2.1 on 2025-10-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_compression', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compressimage',
            name='quality',
            field=models.IntegerField(choices=[(10, '10%'), (20, '20%'), (30, '30%'), (40, '40%'), (50, '50%'), (60, '60%'), (70, '70%'), (80, '80%'), (90, '90%'), (100, '100%')], default=80),
        ),
    ]
