# Generated by Django 5.2.1 on 2025-06-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0002_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('employee_name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
            ],
        ),
    ]
