# Generated by Django 5.2.1 on 2025-06-27 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0004_employee_details'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee_details',
            new_name='Employee_detail',
        ),
    ]
